name: deploy-website
on: 
  push:
    branches: [ mian ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.8.1
      with:
        node-version: "16.x" # optional
    - name: install deps
      run: npm install
    - name: build app
      run: npm run docs:build

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: username/repo
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist
        CNAME: https://www.xxx.com
